kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  data:
    bundles.yml: |
      - name: ansible
        skus:
          - RH00798
          - ESA0016
          - MCT3311
          - MCT3311F3
          - MCT3319
          - MCT3319F3
          - MCT3319RN
          - MCT3319S
          - MCT3320
          - MCT3320F3
          - MCT3320S
          - MCT3321
          - MCT3321F3
          - MCT3321RN
          - MCT3321S
          - MCT3487
          - MCT3487RN
          - MCT3488
          - MCT3488RN
          - MCT3691
          - MCT3691RN
          - MCT3691F3
          - MCT3691F3RN
          - MCT3691S
          - MCT3692
          - MCT3692RN
          - MCT3692F3
          - MCT3692S
          - MCT3693
          - MCT3693F3
          - MCT3693S
          - MCT3694
          - MCT3694RN
          - MCT3694F3
          - MCT3694F3RN
          - MCT3694S
          - MCT3695
          - MCT3695RN
          - MCT3695F3
          - MCT3695F3RN
          - MCT3695S
          - MCT3696
          - MCT3696F3
          - MCT3696S
          - MCT3698
          - MCT3698S
          - MCT3733
          - MCT3733F3
          - MCT3733F3RN
          - MCT3733S
          - MCT3734
          - MCT3742
          - MCT3742F3
          - MCT3742RN
          - MCT3743
          - MCT3743F3
          - MCT3743RN
          - MCT3744
          - MCT3744F3
          - MCT3809
          - MCT3809F3
          - MCT3809F5
          - MCT3810
          - MCT3810F3
          - MCT3810F5
          - MCT3811
          - MCT3811F3
          - MCT3811F5
          - MCT3812
          - MCT3812F3
          - MCT3812F5
          - MCT3813
          - MCT3813F3
          - MCT3813F5
          - MCT3814
          - MCT3814F3
          - MCT3814F5
          - MCT3815
          - MCT3816
          - MCT3817
          - MCT3865
          - MCT3866
          - MCT3866F3
          - MCT3866F3RN
          - MCT3873
          - MCT3873RN
          - MCT3873F3
          - MCT3874
          - MCT3876
          - MCT3876RN
          - MCT3876F3
          - MCT3876S
          - MCT3878
          - MCT3948
          - MCT3948F3
          - MCT4249
          - SER0496
          - SER0497
          - SER0569
          - SER0570
          - SER0764
          - MCT4164
          - MCT4165
          - MCT4164F3
          - MCT4165F3
          - MCT3849
          - MCT3850
          - MCT3991
          - MCT3991F3
          - MCT3991MO
          - MCT3992
          - MCT3992F3
          - MCT3992MO
          - MCT3993
          - MCT3993F3
          - MCT3993MO
          - MCT3994
          - MCT3994F3
          - MCT3994MO
          - MCT3995
          - MCT3995F3
          - MCT3995MO
          - MCT3996
          - MCT3996F3
          - MCT3996MO
          - MCT4019
          - MCT4134
          - MCT4166
          - MCT4166F3
          - MCT4167
          - MCT4167F3
          - MCT4168
          - MCT4168F3
          - MCT4212
          - MCT4212F3
          - MCT4241
          - MCT4391
          - MCT4391F3
          - MCT4392
          - MCT4392F3
          - MCT4522
          - MCT4523
          - MCT4592
          - MCT4592F3
          - MCT4592F5
          - MCT4593
          - MCT4593F3
          - MCT4593F5
          - MCT4594
          - MCT4594F3
          - MCT4594F5
          - MCT4595
          - MCT4595F3
          - MCT4595F5
          - MCT4596
          - MCT4596F3
          - MCT4597
          - MCT4597F3
          - MCT4598
          - MCT4598F3
          - MCT4599
          - MCT4599F3
          - MCT4608
          - MCT4623
          - MCT4623F3
          - MCT4624
          - MCT4624F3
          - MCT4625
          - MCT4625F3
          - MCT4626
          - MCT4626F3
          - MCT4627
          - MCT4627F3
          - MCT4630
          - MCT4630F3
          - MCT4631
          - MCT4631F3
          - MCT4633
          - MCT4633F3
          - MCT4634
          - MCT4634F3
          - MCT4635
          - MCT4635F3
          - MCT4636
          - MCT4636F3
          - MW02049
          - MW02577
          - MW02577F3
          - MW02581
          - MW02581F3
          - RC1257407
          - ES0113909

      - name: cost_management
        use_valid_org_id: true

      - name: insights
        use_valid_org_id: true

      - name: migrations
        use_valid_org_id: true

      - name: subscriptions
        use_valid_org_id: true

      - name: settings
        use_valid_org_id: true

      - name: user_preferences
        use_valid_org_id: true

      - name: openshift
        use_valid_org_id: false

      - name: smart_management
        skus:
          - SVC3124
          - RH00066
          - RH00065
          - RH00798

      - name: internal
        use_is_internal: true

      - name: rhel
        use_valid_org_id: true

      - name: rhods
        skus:
          - MCT4217MO

      - name: rhoam
        skus:
          - MW01459
          - MW01460
          - MW01461
          - MW01462
          - MW01737

      - name: rhosak
        skus:
          - MW01882
          - MW01891
          - MW01892MO

      - name: acs
        skus:
          - MW02162
          - MW02162RN
          - MW02162S
          - MW02162F3
          - MW02162F3RN
          - MW02159
          - MW02159RN
          - MW02159S
          - MW02159F3
          - MW02159F3RN
          - MW02164HR
          - MW02161HR
          - MW02163MO
          - MW02160MO
          - MW02165
          - MW02165RN
          - MW02165S
          - MW02165MO
          - MW02165F3
          - MW02165F3RN
          - MW02166
          - MW02166RN
          - MW02166S
          - MW02166MO
          - MW02166F3
          - MW02166F3RN
          - MW02167
          - MW02167RN
          - MW02167S
          - MW02167HR
          - MW02167MO
          - MW02167F3
          - MW02167F3RN
          - MW02291
          - MW02291RN
          - MW02291S
          - MW02291F3
          - MW02291F3RN
          - MW02404
          - MW02404RN
          - MW02404S
          - MW02404HR
          - MW02404MO
          - MW02404F3
          - MW02404F3RN
          - MW02405
          - MW02405RN
          - MW02405S
          - MW02405HR
          - MW02405MO
          - MW02405F3
          - MW02405F3RN
          - SER0774
          - SER0795
          - SER0798
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: entitlements-config
    annotations:
      qontract.recycle: "true"
